# Generated by Django 2.2.15 on 2022-01-01 16:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='مختصات مکان مبدا')),
                ('destination_location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='مختصات مکان مقصد')),
                ('travel_distance', models.FloatField(default=0.0, help_text='پس از ذخیره تغییرات به روز می شود', verbose_name='فاصله سفر')),
            ],
        ),
    ]
